# Generated by Django 4.1.4 on 2023-01-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genpass',
            options={'ordering': ['user'], 'verbose_name': 'genpass', 'verbose_name_plural': 'genpasses'},
        ),
        migrations.AlterField(
            model_name='genpass',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
