# Generated by Django 4.1.4 on 2023-01-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_genpass_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genpass',
            options={'ordering': ['time'], 'verbose_name': 'genpass', 'verbose_name_plural': 'genpasses'},
        ),
    ]
